export enum ActionTypes {
  ADD_CAR = '[Cars] Add car',
  ADD_CAR_SUCCESS = '[Cars] Add car success',
  ADD_CAR_FAILURE = '[Cars] Add car failure',
  CARS_LIST = '[Cars] Cars List',
  CARS_LIST_SUCCES = '[Cars] Cars List succes',
  CARS_LIST_FAILURE = '[Cars] Cars List failure',
  CARS_LIST_RESET = '[Cars] Cars List reset',
  NO_MORE_CARS_LIST = '[Cars] No more Cars list',
  NO_MORE_CARS_LIST_FALSE = '[Cars] No more Cars list false',
  NO_MORE_CARS_LIST_TRUE = '[Cars] No more Cars list true',
  CAR_DELETE = '[Cars] Car delete',
  CAR_DELETE_SUCCES = '[Cars] Car delete succes',
  CAR_DELETE_FAILURE = '[Cars] Car delete failure',
  UPDATE_STATE_CARS = '[Cars] Update state cars',
  UPDATE_STATE_CARS_SUCCES = '[Cars] Update state cars success',
  UPDATE_STATE_CARS_FAILURE = '[Cars] Update state cars failure',
  CAR_GET_CURRENT = '[Cars] Get car current',
  CAR_GET_CURRENT_SUCCES = '[Cars] Get car current succes',
  CAR_GET_CURRENT_FAILURE = '[Cars] Get car current failure',
  CAR_GET_CURRENT_RESET = '[Cars] Get car current reset',
}
