export enum ActionTypes {
  ADD_SETTING_AVTOPARK = '[Settings] Add setting avtopark',
  ADD_SETTING_AVTOPARK_SUCCESS = '[Settings] Add setting avtopark success',
  ADD_SETTING_AVTOPARK_FAILURE = '[Settings] Add setting avtopark failure',
  SETTINGS_AVTOPARK_LIST = '[Settings] Settings avtopark List',
  SETTINGS_AVTOPARK_LIST_SUCCES = '[Settings] Settings avtopark List succes',
  SETTINGS_AVTOPARK_LIST_FAILURE = '[Settings] Settings avtopark List failure',
  SETTINGS_AVTOPARK_LIST_RESET = '[Settings] Settings avtopark List reset',
  NO_MORE_SETTINGS_AVTOPARK_LIST = '[Settings] No more Settings avtopark list',
  NO_MORE_SETTINGS_AVTOPARK_LIST_FALSE = '[Settings] No more Settings avtopark list false',
  NO_MORE_SETTINGS_AVTOPARK_LIST_TRUE = '[Settings] No more Settings avtopark list true',
  SETTING_AVTOPARK_DELETE = '[Settings] Settings avtopark delete',
  SETTING_AVTOPARK_DELETE_SUCCES = '[Settings] Settings avtopark delete succes',
  SETTING_AVTOPARK_DELETE_FAILURE = '[Settings] Settings avtopark delete failure',
  UPDATE_STATE_SETTINGS = '[Settings] Update state setting avtopark',
  UPDATE_STATE_SETTINGS_SUCCES = '[Settings] Update state setting avtopark success',
  UPDATE_STATE_SETTINGS_FAILURE = '[Settings] Update state setting avtopark failure',
  SETTINGS_AVTOPARK_GET_CURRENT = '[Settings] Get setting avtopark current',
  SETTINGS_AVTOPARK_GET_CURRENT_SUCCES = '[Settings] Get setting avtopark succes',
  SETTINGS_AVTOPARK_GET_CURRENT_FAILURE = '[Settings] Get setting avtopark failure',
  SETTINGS_AVTOPARK_GET_CURRENT_RESET = '[Settings] Get setting avtopark reset',
  UPDATE_SETTINS_AVTOPARK = '[Settings] Update  setting avtopark',
  UPDATE_SETTINS_AVTOPARK_SUCCESS = '[Settings] Update setting avtopark success',
  UPDATE_SSETTINS_AVTOPARK_FAILURE = '[Settings] Update setting avtopark failure',


  ADD_SETTING_SKLAD = '[Settings] Add setting sklad',
  ADD_SETTING_SKLAD_SUCCESS = '[Settings] Add setting sklad success',
  ADD_SETTING_SKLAD_FAILURE = '[Settings] Add setting sklad failure',
  SETTINGS_SKLAD_LIST = '[Settings] Settings sklad List',
  SETTINGS_SKLAD_LIST_SUCCES = '[Settings] Settings sklad List succes',
  SETTINGS_SKLAD_LIST_FAILURE = '[Settings] Settings sklad List failure',
  SETTINGS_SKLAD_LIST_RESET = '[Settings] Settings sklad List reset',
  NO_MORE_SETTINGS_SKLAD_LIST = '[Settings] No more Settings sklad list',
  NO_MORE_SETTINGS_SKLAD_LIST_FALSE = '[Settings] No more Settings sklad list false',
  NO_MORE_SETTINGS_SKLAD_LIST_TRUE = '[Settings] No more Settings sklad list true',
  SETTING_SKLAD_DELETE = '[Settings] Settings sklad delete',
  SETTING_SKLAD_DELETE_SUCCES = '[Settings] Settings sklad delete succes',
  SETTING_SKLAD_DELETE_FAILURE = '[Settings] Settings sklad delete failure',
  SETTINGS_SKLAD_GET_CURRENT = '[Settings] Get setting sklad current',
  SETTINGS_SKLAD_GET_CURRENT_SUCCES = '[Settings] Get setting sklad succes',
  SETTINGS_SKLAD_GET_CURRENT_FAILURE = '[Settings] Get setting sklad failure',
  SETTINGS_SKLAD_GET_CURRENT_RESET = '[Settings] Get setting sklad reset',
  UPDATE_SETTINS_SKLAD = '[Settings] Update  setting sklad',
  UPDATE_SETTINS_SKLAD_SUCCESS = '[Settings] Update setting sklad success',
  UPDATE_SSETTINS_SKLAD_FAILURE = '[Settings] Update setting sklad failure',




  ADD_SETTING_GLOBAL = '[Settings] Add setting global',
  ADD_SETTING_GLOBAL_SUCCESS = '[Settings] Add setting global success',
  ADD_SETTING_GLOBAL_FAILURE = '[Settings] Add setting global failure',
  SETTINGS_GLOBAL_LIST = '[Settings] Settings global List',
  SETTINGS_GLOBAL_LIST_SUCCES = '[Settings] Settings global List succes',
  SETTINGS_GLOBAL_LIST_FAILURE = '[Settings] Settings global List failure',
  SETTINGS_GLOBAL_LIST_RESET = '[Settings] Settings global List reset',
  NO_MORE_SETTINGS_GLOBAL_LIST = '[Settings] No more Settings global list',
  NO_MORE_SETTINGS_GLOBAL_LIST_FALSE = '[Settings] No more Settings global list false',
  NO_MORE_SETTINGS_GLOBAL_LIST_TRUE = '[Settings] No more Settings global list true',
  SETTING_GLOBAL_DELETE = '[Settings] Settings global delete',
  SETTING_GLOBAL_DELETE_SUCCES = '[Settings] Settings global delete succes',
  SETTING_GLOBAL_DELETE_FAILURE = '[Settings] Settings global delete failure',
  SETTINGS_GLOBAL_GET_CURRENT = '[Settings] Get setting global current',
  SETTINGS_GLOBAL_GET_CURRENT_SUCCES = '[Settings] Get setting global succes',
  SETTINGS_GLOBAL_GET_CURRENT_FAILURE = '[Settings] Get setting global failure',
  SETTINGS_GLOBAL_GET_CURRENT_RESET = '[Settings] Get setting global reset',
  UPDATE_SETTINS_GLOBAL = '[Settings] Update  setting global',
  UPDATE_SETTINS_GLOBAL_SUCCESS = '[Settings] Update setting global success',
  UPDATE_SETTINS_GLOBAL_FAILURE = '[Settings] Update setting global failure',
}
