export enum ActionTypes {
  ADD_SETTING_AVTOPARK = '[Settings] Add setting avtopark',
  ADD_SETTING_AVTOPARK_SUCCESS = '[Settings] Add setting avtopark success',
  ADD_SETTING_AVTOPARK_FAILURE = '[Settings] Add setting avtopark failure',
  SETTINGS_AVTOPARK_LIST = '[Settings] Settings avtopark List',
  SETTINGS_AVTOPARK_LIST_SUCCES = '[Settings] Settings avtopark List succes',
  SETTINGS_AVTOPARK_LIST_FAILURE = '[Settings] Settings avtopark List failure',
  SETTINGS_AVTOPARK_LIST_RESET = '[Settings] Settings avtopark List reset',
  NO_MORE_SETTINGS_AVTOPARK_LIST = '[Settings] No more Settings avtopark list',
  NO_MORE_SETTINGS_AVTOPARK_LIST_FALSE = '[Settings] No more Settings avtopark list false',
  NO_MORE_SETTINGS_AVTOPARK_LIST_TRUE = '[Settings] No more Settings avtopark list true',
  SETTING_AVTOPARK_DELETE = '[Settings] Settings avtopark delete',
  SETTING_AVTOPARK_DELETE_SUCCES = '[Settings] Settings avtopark delete succes',
  SETTING_AVTOPARK_DELETE_FAILURE = '[Settings] Settings avtopark delete failure',
  UPDATE_STATE_SETTINGS = '[Settings] Update state setting avtopark',
  UPDATE_STATE_SETTINGS_SUCCES = '[Settings] Update state setting avtopark success',
  UPDATE_STATE_SETTINGS_FAILURE = '[Settings] Update state setting avtopark failure',
  SETTINGS_AVTOPARK_GET_CURRENT = '[Settings] Get setting avtopark current',
  SETTINGS_AVTOPARK_GET_CURRENT_SUCCES = '[Settings] Get setting avtopark succes',
  SETTINGS_AVTOPARK_GET_CURRENT_FAILURE = '[Settings] Get setting avtopark failure',
  SETTINGS_AVTOPARK_GET_CURRENT_RESET = '[Settings] Get setting avtopark reset',
  UPDATE_SETTINS_AVTOPARK = '[Settings] Update  setting avtopark',
  UPDATE_SETTINS_AVTOPARK_SUCCESS = '[Settings] Update setting avtopark success',
  UPDATE_SSETTINS_AVTOPARK_FAILURE = '[Settings] Update setting avtopark failure',
}
