export enum ActionTypes {
  ADD_PARTNER = '[Partners] Add partner',
  ADD_PARTNER_SUCCESS = '[Partners] Add partner success',
  ADD_PARTNER_FAILURE = '[Partners] Add partner failure',
  // CARS_LIST = '[Cars] Cars List',
  // CARS_LIST_SUCCES = '[Cars] Cars List succes',
  // CARS_LIST_FAILURE = '[Cars] Cars List failure',
  // CARS_LIST_RESET = '[Cars] Cars List reset',
  // NO_MORE_CARS_LIST = '[Cars] No more Cars list',
  // NO_MORE_CARS_LIST_FALSE = '[Cars] No more Cars list false',
  // NO_MORE_CARS_LIST_TRUE = '[Cars] No more Cars list true',
  // CAR_DELETE = '[Cars] Car delete',
  // CAR_DELETE_SUCCES = '[Cars] Car delete succes',
  // CAR_DELETE_FAILURE = '[Cars] Car delete failure',
  UPDATE_STATE_PARTNERS = '[Partners] Update state partner',
  UPDATE_STATE_PARTNERS_SUCCES = '[Partners] Update state partner success',
  UPDATE_STATE_PARTNERS_FAILURE = '[Partners] Update state partner failure',
  // CAR_GET_CURRENT = '[Cars] Get car current',
  // CAR_GET_CURRENT_SUCCES = '[Cars] Get car current succes',
  // CAR_GET_CURRENT_FAILURE = '[Cars] Get car current failure',
  // CAR_GET_CURRENT_RESET = '[Cars] Get car current reset',
  // UPDATE_CAR = '[Cars] Update  car',
  // UPDATE_CAR_SUCCESS = '[Cars] Update car success',
  // UPDATE_CAR_FAILURE = '[Cars] Update car failure',
}
