export enum ActionTypes {
  ADD_CLIENT_FIZ = '[ClientsFiz] Add clientFiz',
  ADD_CLIENT_FIZ_SUCCESS = '[ClientsFiz] Add partner success',
  ADD_CLIENT_FIZ_FAILURE = '[ClientsFiz] Add partner failure',
//   PARTNERS_LIST = '[Partners] Partners List',
//   PARTNERS_LIST_SUCCES = '[Partners] Partners List succes',
//   PARTNERS_LIST_FAILURE = '[Partners] Partners List failure',
//   PARTNERS_LIST_RESET = '[Partners] Partners List reset',
//   NO_MORE_PARTNERS_LIST = '[Partners] No more Partners list',
//   NO_MORE_PARTNERS_LIST_FALSE = '[Partners] No more Partners list false',
//   NO_MORE_PARTNERS_LIST_TRUE = '[Partners] No more Partners list true',
//   PARTNER_DELETE = '[Partners] Partner delete',
//   PARTNER_DELETE_SUCCES = '[Partners] Partner delete succes',
//   PARTNER_DELETE_FAILURE = '[Partners] Partner delete failure',
//   UPDATE_STATE_PARTNERS = '[Partners] Update state partner',
//   UPDATE_STATE_PARTNERS_SUCCES = '[Partners] Update state partner success',
//   UPDATE_STATE_PARTNERS_FAILURE = '[Partners] Update state partner failure',
//   PARTNER_GET_CURRENT = '[Partners] Get car current',
//   PARTNER_GET_CURRENT_SUCCES = '[Partners] Get partner current succes',
//   PARTNER_GET_CURRENT_FAILURE = '[Partners] Get partner current failure',
//   PARTNER_GET_CURRENT_RESET = '[Partners] Get partner current reset',
//   UPDATE_PARTNER = '[Partners] Update  partner',
//   UPDATE_PARTNER_SUCCESS = '[Partners] Update partner success',
//   UPDATE_PARTNER_FAILURE = '[Partners] Update partner failure',
// }
