export enum ActionTypes {
  ADD_CLIENT_FIZ = '[ClientsFiz] Add clientFiz',
  ADD_CLIENT_FIZ_SUCCESS = '[ClientsFiz] Add clientFiz success',
  ADD_CLIENT_FIZ_FAILURE = '[ClientsFiz] Add clientFiz failure',
  CLIENTS_FIZ_LIST = '[ClientsFiz] clientFiz List',
  CLIENTS_FIZ_LIST_SUCCES = '[ClientsFiz] clientFiz List succes',
  CLIENTS_FIZ_LIST_FAILURE = '[ClientsFiz] clientFiz List failure',
  CLIENTS_FIZ_LIST_RESET = '[ClientsFiz] clientFiz List reset',
  NO_MORE_CLIENTS_FIZ_LIST = '[ClientsFiz] No more clientFiz list',
  NO_MORE_CLIENTS_FIZ_LIST_FALSE = '[ClientsFiz] No more clientFiz list false',
  NO_MORE_CLIENTS_FIZ_LIST_TRUE = '[ClientsFiz] No more clientFiz list true',
  // PARTNER_DELETE = '[Partners] Partner delete',
  // PARTNER_DELETE_SUCCES = '[Partners] Partner delete succes',
  // PARTNER_DELETE_FAILURE = '[Partners] Partner delete failure',
  UPDATE_STATE_CLIENTS_FIZ = '[ClientsFiz] Update state clientFiz',
  UPDATE_STATE_CLIENTS_FIZ_SUCCES = '[ClientsFiz] Update state clientFiz success',
  UPDATE_STATE_CLIENTS_FIZ_FAILURE = '[ClientsFiz] Update state clientFiz failure',
  // PARTNER_GET_CURRENT = '[Partners] Get car current',
  // PARTNER_GET_CURRENT_SUCCES = '[Partners] Get partner current succes',
  // PARTNER_GET_CURRENT_FAILURE = '[Partners] Get partner current failure',
  // PARTNER_GET_CURRENT_RESET = '[Partners] Get partner current reset',
  // UPDATE_PARTNER = '[Partners] Update  partner',
  // UPDATE_PARTNER_SUCCESS = '[Partners] Update partner success',
  // UPDATE_PARTNER_FAILURE = '[Partners] Update partner failure',
}
