export enum ActionTypes {
  ADD_CLIENT_FIZ = '[ClientsFiz] Add clientFiz',
  ADD_CLIENT_FIZ_SUCCESS = '[ClientsFiz] Add clientFiz success',
  ADD_CLIENT_FIZ_FAILURE = '[ClientsFiz] Add clientFiz failure',
  CLIENTS_FIZ_LIST = '[ClientsFiz] clientFiz List',
  CLIENTS_FIZ_LIST_SUCCES = '[ClientsFiz] clientFiz List succes',
  CLIENTS_FIZ_LIST_FAILURE = '[ClientsFiz] clientFiz List failure',
  CLIENTS_FIZ_LIST_RESET = '[ClientsFiz] clientFiz List reset',
  NO_MORE_CLIENTS_FIZ_LIST = '[ClientsFiz] No more clientFiz list',
  NO_MORE_CLIENTS_FIZ_LIST_FALSE = '[ClientsFiz] No more clientFiz list false',
  NO_MORE_CLIENTS_FIZ_LIST_TRUE = '[ClientsFiz] No more clientFiz list true',
  CLIENT_FIZ_DELETE = '[ClientsFiz] clientFiz delete',
  CLIENT_FIZ_DELETE_SUCCES = '[ClientsFiz] clientFiz delete succes',
  CLIENT_FIZ_DELETE_FAILURE = '[ClientsFiz] clientFiz delete failure',
  UPDATE_STATE_CLIENTS_FIZ = '[ClientsFiz] Update state clientFiz',
  UPDATE_STATE_CLIENTS_FIZ_SUCCES = '[ClientsFiz] Update state clientFiz success',
  UPDATE_STATE_CLIENTS_FIZ_FAILURE = '[ClientsFiz] Update state clientFiz failure',
  CLIENT_FIZ_GET_CURRENT = '[ClientsFiz] Get car current',
  CLIENT_FIZ_GET_CURRENT_SUCCES = '[ClientsFiz] Get clientFiz current succes',
  CLIENT_FIZ_GET_CURRENT_FAILURE = '[ClientsFiz] Get clientFiz current failure',
  CLIENT_FIZ_GET_CURRENT_RESET = '[ClientsFiz] Get clientFiz current reset',
  // UPDATE_PARTNER = '[Partners] Update  partner',
  // UPDATE_PARTNER_SUCCESS = '[Partners] Update partner success',
  // UPDATE_PARTNER_FAILURE = '[Partners] Update partner failure',
}
