export enum ActionTypes {
  REGISTER = '[Account] Register',
  REGISTER_SUCCESS = '[Account] Register success',
  REGISTER_FAILURE = '[Account] Register failure',
  LOGIN = '[Account] Login',
  LOGIN_SUCCESS = '[Account] Login success',
  LOGIN_FAILURE = '[Account] Login failure',
  LOGOUT = '[Account] Logout',
  LOGOUT_SUCCESS = '[Account] Logout success',
  LOGOUT_FAILURE = '[Account] Logout failure',
  UPDATE_STATE = '[Account] Update state',
  UPDATE_STATE_SUCCESS = '[Account] Update state success',
  UPDATE_STATE_FAILURE = '[Account] Update state failure',
  UPDATE_USER = '[Account] Update  user',
  UPDATE_USER_SUCCESS = '[Account] Update user success',
  UPDATE_USER_FAILURE = '[Account] Update user failure',
}
